# Generated by Django 5.2.17 on 2026-09-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classroom_class_teacher_alter_grade_term_and_more'),
        ('students', '0002_student_classroom_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='date_conducted',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='max_score',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assessment')},
        ),
        migrations.AddField(
            model_name='assessment',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.CharField(default='Second Term', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='ca_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='academics.assessment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='grade',
            name='score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='term',
        ),
    ]
